### ISSUE TITLE
Npc Vendedor de monturas issues

### ISSUE THREAD

**Issue by davidzoque** [ColossusWoW/ColossusWoW-Legion-Bugtracker#1]
El npc encargado de vender monturas de la raza Orca no vende nada.

http://es.wowhead.com/npc=3362/ogunaro-correlobo

El npc encargado de vender monturas de la raza elfo de noche no vende nada.

http://es.wowhead.com/npc=4730/lelanai

**Comment by Ragebones** [comment]
Corregido
