### ISSUE TITLE
Sus números son legión [Misión] 

### ISSUE THREAD

**Issue by Drakfire** [ColossusWoW/ColossusWoW-Legion-Bugtracker#103]
he reportado, anteriormente la misión sobre otro fallo, y tengo otro nuevo. cuando abandone la misión para volver a hacerla, ya no la vuelve a dar.
Misión : http://es.wowhead.com/quest=38819/sus-numeros-son-legion
NPC de completar: http://es.wowhead.com/npc=93127/kayn-furia-del-sol
NPC que la da: http://es.wowhead.com/npc=96420/cyana-gujasombria

**Comment by searum** [comment]
A ver, si no somos pacientes y esperamos a que actualicemos el emulador entonces jamás vas a ver ningún arreglo.

Dejar de abrir issues repetidos. Si a caso, si pasan 48h de un anuncio de fix y no está aplicado en el servidor, volver a abrir el issue pero no creéis ninguno nuevo.
