### ISSUE TITLE
[Spell] metamorfosis

### ISSUE THREAD

**Issue by Drakfire** [ColossusWoW/ColossusWoW-Legion-Bugtracker#108]
Al caer no hace daño, ni aturde a los enemigos. Aparte cuando cae, cae muy lento y los enemigos te están pegando antes de tocar el suelo. (Tendría que caer mas rápido )
y se tiene que transformar al aterrizar, no al darle a la spell
http://es.wowhead.com/spell=191427/metamorfosis

**Comment by timh52280** [comment]
Fix
