### ISSUE TITLE
"Haz" lo que hay que hacer - Misión

### ISSUE THREAD

**Issue by Drakfire** [ColossusWoW/ColossusWoW-Legion-Bugtracker#109]
Al darle al espejo, no se gira, no se completa la misión. no sabría explicarte, mejor te dejo un vídeo.
Vídeo explicativo: 
https://www.youtube.com/watch?v=pNYdKfucIk8&feature=youtu.be
MISIÓN:
http://es.wowhead.com/quest=39684/beam-me-up

**Comment by searum** [comment]
fix
