### ISSUE TITLE
Némesis [Spell]

### ISSUE THREAD

**Issue by Drakfire** [ColossusWoW/ColossusWoW-Legion-Bugtracker#117]
Tal y como pone la habilidad 
_Aumenta un 20% el daño que infliges al objetivo durante 1 min.
**Cuando el objetivo muera, infligirás un 20% más de daño contra todas las criaturas del mismo tipo que el objetivo original (humanoide, dragonante, etc.) durante su tiempo restante._**_
Al matar a la criatura no hace su efecto del 40% mas de daño.
Spell: http://es.wowhead.com/spell=206491/nemesis

**Comment by timh52280** [comment]
Fixed
