### ISSUE TITLE
Evento de halloween 2

### ISSUE THREAD

**Issue by renzo101999** [ColossusWoW/ColossusWoW-Legion-Bugtracker#118]
Las varitas no funcionan no se puede convertir a otro pj para el logro http://es.wowhead.com/achievement=283/la-mascarada

Murcielago:    http://es.wowhead.com/spell=24733/traje-de-murcielago
Gnomo paria:     http://es.wowhead.com/spell=24719/traje-de-gnomo-paria
Pirata:     http://es.wowhead.com/spell=24717/traje-de-pirata
Fuego fatuo:   http://es.wowhead.com/spell=24741/traje-de-fuego-fatuo
Fantasma:   http://es.wowhead.com/spell=24737/traje-de-fantasma
Traje de ninja:  http://es.wowhead.com/spell=24718/traje-de-ninja
Traje de esqueleto:  http://es.wowhead.com/spell=24724/traje-de-esqueleto

**Comment by timh52280** [comment]
Si funcionan las varitas solo que con quien las uses deben de estar en grupo contigo
