### ISSUE TITLE
Jefes de Mundo Pandaria

### ISSUE THREAD

**Issue by renzo101999** [ColossusWoW/ColossusWoW-Legion-Bugtracker#119]
1.. EL SHA DE LA IRA.-   http://es.wowhead.com/npc=60491/sha-de-la-ira
no da loot al intentar despojar 
Montura:  http://es.wowhead.com/item=87771/riendas-del-dragon-nimbo-onice-celico

2.. OONDASTA.-   http://es.wowhead.com/npc=69161/oondasta
No se encuentra el NPC
Montura:  http://es.wowhead.com/item=94228/riendas-del-cuernoatroz-primario-de-cobalto

3.. GALEÓN.-      http://es.wowhead.com/npc=62346/galeon
No se encuentra el NPC
Montura: http://es.wowhead.com/item=89783/silla-de-montar-del-hijo-de-galeon

4.. NALAK.-   http://es.wowhead.com/npc=69099/nalak
No te dan la misión http://es.wowhead.com/quest=32678/la-llamada-del-trueno
que te inicia las misiones para ir a las Islas del trueno http://es.wowhead.com/isle-of-thunder

**Comment by searum** [comment]
fix
