### ISSUE TITLE
[Misión] El portal oscuro

### ISSUE THREAD

**Issue by renzo101999** [ColossusWoW/ColossusWoW-Legion-Bugtracker#120]
La misión del portal oscuro http://es.wowhead.com/quest=34398/el-portal-oscuro
No se le puede hablar para continuar con la cadena de misiones http://es.wowhead.com/npc=78419/speak-with-khadgar-credit

**Comment by rksmw** [comment]
Hola :) ya esta solucionado aquí un vídeo https://www.youtube.com/watch?v=POvymX5Jpyc&feature=youtu.be

**Comment by renzo101999** [comment]
Gracias por el vídeo

**Comment by renzo101999** [comment]
No funciona aca una foto de prueba
http://www.uppic.es/image/0R9

**Comment by rksmw** [comment]
lo que pasa es que los devs los probamos en otro reino antes de ponerlo en el real , en estos dias se aplicara la corrección de spells y este script

**Comment by searum** [comment]
fix
