### ISSUE TITLE
Sistema de recompensas de misiones bugs

### ISSUE THREAD

**Issue by davidzoque** [ColossusWoW/ColossusWoW-Legion-Bugtracker#15]
En la mayoria de misiones no otorgan las recompensas que afirman dar tales como oro, items etc. Tciket bug ID= 27.

**Comment by davidzoque** [comment]
Ticket id bug: 28.

**Comment by Misimouse** [comment]
Gracias por informar, si pudieras poner las misiones que te han dado este problema ayudaría mucho porque sino vamos a tener que mirarlas todas y es bastante inviable, gracias.

**Comment by davidzoque** [comment]
Se que es bastante inviable, pero son tantas que anotarlas lo hace casi igual, ademas que despues de ntregada es que uno se da cuenta.

**Comment by tomasgx** [comment]
bueno puede comenzar con la de los inicio y de hay seguir por los mapas como si estuvieran leveleando, por que son casi un 100%, yo he estado jugando con un pala, he jugado desde villanorte a vegatuercaespina y en ninguna de esos territorios de lvl donde se pasa me dieron lo que me decian las misiones.

**Comment by searum** [comment]
necesito alguna misión para ver que es lo que sucede, si es general del emulador o es que faltan datos o son incorrectos en la base de datos...

**Comment by searum** [comment]
el sistema de recompensas de misiones lo he probado y funciona correctamente, tal vez pueda fallar alguna misión, vuelve a probar y si falla alguna misión reporta la misión pero yo he obtenido reputación, items, oro, experiencia... y esto en la zona de Gilneas

**Comment by kinburguer** [comment]
pero men arregla todas porque de nivel 20 en adelante ninguna te da item y es muy duro en los demon hunter y demas
