### ISSUE TITLE
bug demon hunter De vuelta al templo oscuro

### ISSUE THREAD

**Issue by daco9312** [ColossusWoW/ColossusWoW-Legion-Bugtracker#151]
Mi Demon hunter aun no funciona aun después de que colocaron "fixed" a mi otra entrada. ¿Que debo hacer para arreglar eso?. Ya he enviado un montón de tickets ingame y vuelvo a abrir el post aquí.

el nombre de mi pj es judgefree

muchas gracias

**Comment by timh52280** [comment]
describe el problema por favor

**Comment by searum** [comment]
Debes de estar conectado coincidiendo con algun gm para que pueda ayudarte.. Trata de ponerte en contacto si no con algún gm desde el foro. http://colossuswow.com/forums.

Un saludo.
