### ISSUE TITLE
Pandaria Bug

### ISSUE THREAD

**Issue by Tovarashi** [ColossusWoW/ColossusWoW-Legion-Bugtracker#158]
en si todo pandari en cuestiones de leveo esta bugs los enemigos no dan exp, ni explorar da experincia
asi como bugs de misones que no se compleetan
![wowscrnshot_110616_171658](https://cloud.githubusercontent.com/assets/23303443/20045247/16977f7c-a465-11e6-8888-1671b824df6b.jpg)
![wowscrnshot_110616_171919](https://cloud.githubusercontent.com/assets/23303443/20045248/169b929c-a465-11e6-8f3c-9f43a2c333dc.jpg)
![wowscrnshot_110616_171926](https://cloud.githubusercontent.com/assets/23303443/20045249/169cedfe-a465-11e6-9fdb-1f85c0e5655e.jpg)
![wowscrnshot_110616_172456](https://cloud.githubusercontent.com/assets/23303443/20045250/169ed402-a465-11e6-9e8c-69174ef83ff5.jpg)
![wowscrnshot_110616_172714](https://cloud.githubusercontent.com/assets/23303443/20045251/16a3e708-a465-11e6-94d6-c0eb7f841221.jpg)
![wowscrnshot_110616_173417](https://cloud.githubusercontent.com/assets/23303443/20045252/16a55ae8-a465-11e6-8379-6386705246d6.jpg)
![wowscrnshot_110616_173650](https://cloud.githubusercontent.com/assets/23303443/20045253/16aee662-a465-11e6-89fa-315174ad0eb9.jpg)
![wowscrnshot_110616_183842](https://cloud.githubusercontent.com/assets/23303443/20045254/16b2fd24-a465-11e6-9e1a-806eeae381f0.jpg)

 bug los

**Comment by thebigfer94** [comment]
Seria mas facil si comentaras el ID de los NPC. Gracias por el Reporte

**Comment by Tovarashi** [comment]
para dar el id de los NPC diria tooooooooooooooooooooooooooda pandaria esta bug

**Comment by searum** [comment]
fix la mayoria de pandaria
