### ISSUE TITLE
Mi DH esta to bug T.T 

### ISSUE THREAD

**Issue by BlakWoW** [ColossusWoW/ColossusWoW-Legion-Bugtracker#159]
no me funcionan las sig. habilidades..
-Haz ocular
-Danza de hojas
-Metamorfosis 
   No funciona de ninguna manera estube golpeando bichos todo el rato asta llenar mi barra y no sale el poder..
![wowscrnshot_110716_161601](https://cloud.githubusercontent.com/assets/23320753/20072021/929f51e4-a505-11e6-8a71-231421f1d132.jpg)
![wowscrnshot_110716_161550](https://cloud.githubusercontent.com/assets/23320753/20072022/92a1756e-a505-11e6-9e71-5d46a2c7f473.jpg)

Golpe de caos si me funciona( cuando tengo ira claro),eso muestra que si me funciona la ira pero no se porque no me deja usar esas habilidades, cuando creo el personaje esas habilidades no me salen en la barra tengo que ponerlas manualmete (recree el personaje ya pero sigue igual) aun asi cuando relogueo se salen de mi barra esos poderes..
cuando termine la historia de los DH aun seguia sin dejarme usar los poderes lo que no he probado es si puedo usarlos al 110 ya que solo llegue asta el 108 pero hable con un amigo y a el si le dejaba usarlos y era 98... estube hablando con un MJ y me dijo que era un bug visual y que no tenia ira por eso no podria usarlo pero golpe de caos usa ira y si podia usarlo

**Comment by searum** [comment]
Es que esas habilidades las aprendes haciendo misiones, por eso no funcionan. Hasta que no hagas las misiones no las vas a poder usar.

Saludos.

**Comment by BlakWoW** [comment]
:O grasias pero que misiones me dan esas habilidades? no encontre ninguna que me las de pero buscare mejor :D
