### ISSUE TITLE
INSTA 85 no funciona.. 

### ISSUE THREAD

**Issue by BlakWoW** [ColossusWoW/ColossusWoW-Legion-Bugtracker#160]
mi recluta y yo compartimos la misma red

**Comment by Tovarashi** [comment]
ahi el problema xD eso es con un gm xD

**Comment by BlakWoW** [comment]
xD me dijo que no tenian nada que ver que hable aca xDD

**Comment by searum** [comment]
Esto no va aquí. Es un tema de Ingame o foro.

Es un personaje por IP.
