### ISSUE TITLE
Demon Hunter Inicios Bug

### ISSUE THREAD

**Issue by Tovarashi** [ColossusWoW/ColossusWoW-Legion-Bugtracker#162]
las primeras misiones del DH no funcionan no las puedes completar ya que los objetos no salen veace el estandarte o los npc de la segunda mision 
![wowscrnshot_110716_224628](https://cloud.githubusercontent.com/assets/23303443/20114912/dd9da658-a5bb-11e6-8848-c76e2c3bd0a8.jpg)
![wowscrnshot_110716_224631](https://cloud.githubusercontent.com/assets/23303443/20114913/dda09a2a-a5bb-11e6-950e-28abac739a5b.jpg)
![wowscrnshot_110716_225602](https://cloud.githubusercontent.com/assets/23303443/20114914/dda29df2-a5bb-11e6-9678-92b78e44f6b1.jpg)
![wowscrnshot_110716_225609](https://cloud.githubusercontent.com/assets/23303443/20114915/ddaa0182-a5bb-11e6-83c9-c651267952d7.jpg)

**Comment by searum** [comment]
funcionan, debes esperar a que te descargue el juego un poco más y te carguen los objetos.

**Comment by BlakWoW** [comment]
yo la complete 2 veses :)
