### ISSUE TITLE
Misiones y enemigos bugs en Pandaria.

### ISSUE THREAD

**Issue by Crackares** [ColossusWoW/ColossusWoW-Legion-Bugtracker#166]
![wowscrnshot_110916_142508](https://cloud.githubusercontent.com/assets/23349633/20147833/9603432a-a688-11e6-9559-6bef90145828.jpg)
![wowscrnshot_110916_142515](https://cloud.githubusercontent.com/assets/23349633/20147834/9614a4e4-a688-11e6-9f4e-6f7766e1ff47.jpg)
![wowscrnshot_110916_142518](https://cloud.githubusercontent.com/assets/23349633/20147835/961cf392-a688-11e6-8f14-a4e1ceb90efd.jpg)
![wowscrnshot_110916_142530](https://cloud.githubusercontent.com/assets/23349633/20147836/96252d1e-a688-11e6-9b3f-160a051000cc.jpg)

**Comment by Tovarashi** [comment]
pandaria es un dolor de muelas :´v

**Comment by searum** [comment]
fix
