### ISSUE TITLE
Demon hunter mision bug/warrior ataque bug/portal draenor/ costas abruptas

### ISSUE THREAD

**Issue by elhuesoss** [ColossusWoW/ColossusWoW-Legion-Bugtracker#175]
Al acabar las misiones de la primera face y completar la mision de vuelta al portal oscuro, la pantalla no carga, y sale wow error, cuando se vuelve a logear la pantalla aparece en negro y solo se puede ver con el hechizo de la vision arreglen ese bug, he creado mas de 12 veces el demon hunter y no se puede hacer nada.
Embate en el guerrero esta bug, no cumple lo que hace con su pasivo de reutilisacion de proc asi que arreglen por favor esos bug.
ya que no pueden hacer misiones que no esten bug, almenos pongan portales para poder ir a las principales ciudades de esas zonas
GRACIAS.

**Comment by searum** [comment]
fix
