### ISSUE TITLE
problemas en dh

### ISSUE THREAD

**Issue by Drakfire** [ColossusWoW/ColossusWoW-Legion-Bugtracker#176]
Al acabar la misión de [vuelta al templo oscuro ](http://es.wowhead.com/quest=38729/vuelta-al-templo-oscuro) te mandan a la cámara del silencio que está dentro de la [cámaras de las celadoras ](http://es.wowhead.com/vault-of-the-wardens) 
cuando carga tendría que salir una cinemática  y al no salir, no carga la pantalla. entonces tengo que cerrar wow. cuando vuelvo a entrar esta mi pantalla en negro y no se ve nada, solo si le doy a visión espectral durante unos 10 segundos me deja ver, pero luego vuelta en negro.
solo le quita la pantalla en negro si un gm te hace .unaura all

**Comment by searum** [comment]
fix y otra vez repetido... USAR EL BUSCADOR!
