### ISSUE TITLE
Lista de skills bug en el PALADIN

### ISSUE THREAD

**Issue by Killerbeer1** [ColossusWoW/ColossusWoW-Legion-Bugtracker#178]
Consagracion Paladin protect 
http://www.wowhead.com/spell=205228
El skill no inflige el daño correspondiente al 30% del  poder de ataque si no que hace 300 punto de daño siempre

Consagracion Paladin Represion 
Talento Nivel 15
http://www.wowhead.com/spell=205228
El skill de la rama represio no hace ningun tipo de daño a diferencia de la consagracion del paladin proteccion 

Intervencion divina Paladin Represion
Talento Nivel 90
http://www.wowhead.com/spell=213313
El talento otorga inmortalidad al usuario en lugar de Reduce un 50% el tiempo de reutilización de Escudo divino. Además, todo ataque que debiera matarte reduce tu salud a un 20% de tu salud máxima y activa Escudo divino. 

Ojo de tyr Skill de ARTEFACTO  paladin proteccion
http://www.wowhead.com/spell=209202
El skill proporciona el debuff de 25% menos de daño a los enemigos pero no hace el daño que deberia que es del 270% del poder de ataque 

Escudo del honrado Skill del paladin Proteccion
http://www.wowhead.com/spell=53600
No otorga la reduccion de daño correspondiente a la maestria del usuario y su daño es desmensurado y no hace el aumento de la reduccion de daño de el 25 %+ en consagracion 

Luz del alba Skill paladin sagrado 
http://www.wowhead.com/spell=85222
No cura a los 5 aliados que deberia curar

Escudo de vengador 
http://www.wowhead.com/spell=31935
No salta sobre los 2 enemigos correspondientes y no otorga el silencion ni la interrupcion 

Gran cruzado Pasiva paladin proteccion 
http://www.wowhead.com/spell=85043
No se activa con martillo del honrado

Luz del protecto Skill Paladin Proteccion 
http://www.wowhead.com/spell=184092
No sala al paladin el 30% de su salud faltante y tampoco hace reaccion con consagracion para el aumento del 20%+

Martillo del honrado Paladin
http://www.wowhead.com/spell=53595
No hace la onda de choque en consagracion

**Comment by searum** [comment]
te lo cierro porque lo has reportado ya como 7 veces las mismas cosas... y ya cansa.
