### ISSUE TITLE
Lista de skills bug en el CAZADOR

### ISSUE THREAD

**Issue by Killerbeer1** [ColossusWoW/ColossusWoW-Legion-Bugtracker#180]
Disparo penetrante Talento lvl 100 Cazador punteria
http://www.wowhead.com/spell=198670
Daño desmensurado del disparo penetrante 64millones por disparo penetrante y en critico 169 millones 
cuando su media de daño deberia ser 500k-600k dependiendo de la marca del cazador 

Disparo vinculante 
http://www.wowhead.com/spell=109248
El disparo vinculante de entrada no da sus 3 segundos de stun y no funciona

Marca del cazador 
http://www.wowhead.com/spell=185987
No se pone la marca de cazador al momento de golpear un objetivo

**Comment by searum** [comment]
fix todo
