### ISSUE TITLE
Lista de skills bug en el DK

### ISSUE THREAD

**Issue by Killerbeer1** [ColossusWoW/ColossusWoW-Legion-Bugtracker#182]
Aliento de sindragosa talento nivel 100 DK Escarcha 
http://www.wowhead.com/spell=152279
El aliento de sindragosa no hace el daño que deberia si no que tambien es infinito no consume las runas

Atraccion letal DK 
http://www.wowhead.com/spell=49576
No atrae al usuario en el que se usa

**Comment by searum** [comment]
fix la primera y la segunda me funciona bien, miraré el scriptname que esté puesto. gracias.
