### ISSUE TITLE
Lista de BUG de CHAMAN  #HECHIZO

### ISSUE THREAD

**Issue by Killerbeer1** [ColossusWoW/ColossusWoW-Legion-Bugtracker#183]
Tótem de Oleada de relámpagos Talento 
http://www.wowhead.com/spell=192058
No funciona pasa lo mismo que con el disparo vinculante del cazador no sale y no posee icono ingame y tiene forma de cuadro y no causa efecto alguno 

Tótem Pillaterra
http://www.wowhead.com/spell=51485
No funciona pasa lo mismo que con el disparo vinculante del cazador no sale y no posee icono ingame y tiene forma de cuadro y no causa efecto alguno 

Tótem vudú
http://www.wowhead.com/spell=196932
No funciona pasa lo mismo que con el disparo vinculante del cazador no sale y no posee icono ingame y tiene forma de cuadro y no causa efecto alguno 

Totem de carga de viento
http://www.wowhead.com/spell=192077
No funciona pasa lo mismo que con el disparo vinculante del cazador no sale y no posee icono ingame y tiene forma de cuadro y no causa efecto alguno 

Totem de escudo de tierra
http://www.wowhead.com/spell=198838
No funciona pasa lo mismo que con el disparo vinculante del cazador no sale y no posee icono ingame y tiene forma de cuadro y no causa efecto alguno

Totem de rafaga de nubes
http://www.wowhead.com/spell=157153
No funciona pasa lo mismo que con el disparo vinculante del cazador no sale y no posee icono ingame  y tiene forma de cuadro y no causa efecto alguno

Totem de magma 
http://www.wowhead.com/spell=192222
No funciona pasa lo mismo que con el disparo vinculante del cazador no sale y no posee icono ingame  y tiene forma de cuadro y no causa efecto alguno

Tótem Corriente de sanación
http://www.wowhead.com/spell=5394
No funciona pasa lo mismo que con el disparo vinculante del cazador no sale y no posee icono ingame  y tiene forma de cuadro y no causa efecto alguno

Tótem de Marea de sanación
http://www.wowhead.com/spell=108280
No funciona pasa lo mismo que con el disparo vinculante del cazador no sale y no posee icono ingame  y tiene forma de cuadro y no causa efecto alguno

Tótem de Golpe de contraataque
http://www.wowhead.com/spell=204331
No funciona pasa lo mismo que con el disparo vinculante del cazador no sale y no posee icono ingame  y tiene forma de cuadro y no causa efecto alguno

Elemental de Fuego
http://www.wowhead.com/spell=198067
No funciona pasa lo mismo que con el disparo vinculante del cazador no sale y no posee icono ingame  y tiene forma de cuadro y no causa efecto alguno

Elemental de Tierra
http://www.wowhead.com/spell=198103
No funciona pasa lo mismo que con el disparo vinculante del cazador no sale y no posee icono ingame  y tiene forma de cuadro y no causa efecto alguno

Espirtu Feral Chaman MEJORA
http://www.wowhead.com/spell=51533
No invoca los respectivos lobos que lo curen durante 15 segundos 

Oleada de sanacion
http://www.wowhead.com/spell=188070
No cura al completar castearse 

Tótem derribador
http://www.wowhead.com/spell=204336
No funciona pasa lo mismo que con el disparo vinculante del cazador no sale y no posee icono ingame  y tiene forma de cuadro y no causa efecto alguno

Tótem Enlace de espíritu
http://www.wowhead.com/spell=98008
No funciona pasa lo mismo que con el disparo vinculante del cazador no sale y no posee icono ingame  y tiene forma de cuadro y no causa efecto alguno

Tótem Furia del cielo
http://www.wowhead.com/spell=204330
No funciona pasa lo mismo que con el disparo vinculante del cazador no sale y no posee icono ingame  y tiene forma de cuadro y no causa efecto alguno

Tótem Viento Furioso
http://www.wowhead.com/spell=204332
No funciona pasa lo mismo que con el disparo vinculante del cazador no sale y no posee icono ingame  y tiene forma de cuadro y no causa efecto alguno

**Comment by searum** [comment]
fix
