### ISSUE TITLE
Bajo daño de spells Mago

### ISSUE THREAD

**Issue by davidzoque** [ColossusWoW/ColossusWoW-Legion-Bugtracker#19]
-La habilidad de la pet de mago Descarga Acuatica (http://es.wowhead.com/spell=31707/descarga-acuatica) inflinge un bajo daño que no esta acorde con lo que el texto dice.
- La habilidad Nova de Escarcha  (http://es.wowhead.com/spell=122/nova-de-escarcha) posee un reducido daño por debajo de lo normal.

**Comment by searum** [comment]
fix
