### ISSUE TITLE
Bug de la zona de leveo de pandaria

### ISSUE THREAD

**Issue by Azufrex** [ColossusWoW/ColossusWoW-Legion-Bugtracker#192]
La Mision:ID:31978 ¡Prioridades! en Pandaria, el bosque de jade en la granja almíbar esta defectuosa ya que consiste en recojer 6 barricas de birramiel y basicamente este dicho objeto al darle click al barril no te da el objeto de la mision. El npc que te da la mision es Gi-Oh ID:66662

La Mision:ID:31773 Problemas con los merodeadores, no se puede realizar ya que no puedes atacar a los sha-infested prowier NPC ID:66668 y la mision consiste en matarlos y esta accion no se puede realizar. El npc que te da la mision es Kai-Lin honeydew ID:66841La Mision:ID:29620 el gran festín, consiste en hablar con el gran maestro, High elder cloudfall ID:54914 y al hablar con el no ocurre nada precionas al boton continuar y no pasa absolutamente nada la mision no se completa.

La Mision:ID:29633 zhi-zhi el diestro, no se puede realizar ya que al hablar con este npc(zhi-zhi ID:54924) no ocurre nada lo que debe pasar es que al hablar con el combatan pero no pasa absolutamente nada al hablar con el.

La Mision:ID:29632 preparándose para la batalla, no se puede realizar ya que consiste en hablar con los npc(tian pupil ID:54944) y al momento de hablar con ellos se enfrenten a una batalla y al hablar con ellos no pasa absolutamente nada.

La Mision:ID:29622 tu entrenamiento comienza ahora, que es una quest auto completable. no se encuentra el npc al que se le debe entregar(Xann) y por ese motivo es imposible completarla.

La Mision:ID:29628 una espalda fuerte, no se puede completar ya que el objeto que la mision te pide(caldera de ebullición) no se encuentra en la zona que te asigna dicha mision,el objeto no aparece.

La Mision:ID:31230 Bienvenidos a floralba, no se puede completar ya que pide que hables con 3 npc(Kai Wanderbrew ID:59173, Master windfur ID:59160,peiji brisa dorada y este ultimo ni siquiera esta en el lugar asignado)al hablar con ellos no pasa absolotumente nada no se completan los objetivos puesto que es imposible de completar.

La Mision:ID:29993 encontrar al muchacho, es una mision autocompletable, el problema es que al ir al punto asignado el npc al que se le entregara la mision no esta.

La Mision:ID:29925 todo lo que hemos podido conseguir, es una misión autocompletable, el problema es que al ir al punto asignado el npc al que se le entregara la misión no esta.

La Mision:ID:29617 Monasterio Tian, es una mision autocompletable, el problema es que al ir al punto asignado el npc al que se le entregara la misión no esta.

**Comment by searum** [comment]
fix
