### ISSUE TITLE
Mision issue

### ISSUE THREAD

**Issue by davidzoque** [ColossusWoW/ColossusWoW-Legion-Bugtracker#21]
El npc debe volverse amistosos depsues de derrotarle para entregar la mision, pero no lo hace sigue como enemigo.

Npc a fixear:
http://es.wowhead.com/npc=19456/espiritu-de-cortezablanca

Mision como deberia funcionar.
https://www.youtube.com/watch?v=rgIufKE-e1Q&feature=youtu.be

**Comment by Misimouse** [comment]
Ok, corregida estará disponible en el siguiente reinicio del server.
