### ISSUE TITLE
apetito demoniaco

### ISSUE THREAD

**Issue by Drakfire** [ColossusWoW/ColossusWoW-Legion-Bugtracker#215]
La habilidad[ apetito demoniaco](http://es.wowhead.com/spell=206478/apetito-demoniaco) tendria que pasar que cuando uses [golpe de caos](http://es.wowhead.com/spell=162794/golpe-de-caos) tiene una probabilidad de generar un trozo de alma inferior, y consumir cualquier trozo de alma otorga 30 p. de furia.

**Comment by searum** [comment]
fix
