### ISSUE TITLE
resurgimiento de demonio

### ISSUE THREAD

**Issue by Drakfire** [ColossusWoW/ColossusWoW-Legion-Bugtracker#218]
la habilidad [resurgimiento de demonio](http://es.wowhead.com/spell=193897/resurgimiento-de-demonio)
tendría que al usar [metamorfosis ](http://es.wowhead.com/spell=191427/metamorfosis) reinicie las habilidades de [haz ocular](http://es.wowhead.com/spell=198013/haz-ocular), [nova de caos](http://es.wowhead.com/spell=179057/nova-de-caos), [disiparse](http://es.wowhead.com/spell=198589/disiparse)

**Comment by searum** [comment]
fix
