### ISSUE TITLE
Spell Congracion Paladin Proteccion,Sagrado

### ISSUE THREAD

**Issue by Killerbeer1** [ColossusWoW/ColossusWoW-Legion-Bugtracker#221]
El spell consagracion hace 315 de daño al usarse,en lugar de hacer los 30% del poder de ataque de usuario
tampoco otorga los beneficios extra en Curacion del mano del protector y el aumento de reduccion de daño de escudo del honrado 
http://es.wowhead.com/spell=26573/consagracion

**Comment by searum** [comment]
fix, un error tonto era :p
