### ISSUE TITLE
SPELL ESCUDO DEL VENGADOR-PALADIN 

### ISSUE THREAD

**Issue by Killerbeer1** [ColossusWoW/ColossusWoW-Legion-Bugtracker#223]
El daño de escudo de vengador es 1 en lugar de hacer el daño de 435% del poder de ataque del usuario esto segun el change log de 7.1.0 (Mon Oct 24 2016) Build 22758 
http://es.wowhead.com/spell=31935/escudo-de-vengador#changelog

**Comment by searum** [comment]
fix
