### ISSUE TITLE
SPELL ESCUDO DEL HONRADO-PALADIN

### ISSUE THREAD

**Issue by Killerbeer1** [ColossusWoW/ColossusWoW-Legion-Bugtracker#224]
El escudo del honrado tiene un daño de 1 p de daño sagrado en lugar de hacer el daño de 400% de poder de ataque del usuario,tampoco otorga la reducción de daño del 25%  y en consagración no da el 20% extra 
por 4.5 segundos esto según elchange log  7.1.0 (Mon Oct 24 2016) Build 22758

http://es.wowhead.com/spell=53600/escudo-del-honrado#changelog

**Comment by searum** [comment]
fix
