### ISSUE TITLE
SPELL DESTELLO DE LUZ-PALADIN-SAGRADO,PROTECCION,REPRESION

### ISSUE THREAD

**Issue by Killerbeer1** [ColossusWoW/ColossusWoW-Legion-Bugtracker#225]
EL DESTELLO DE LUZ CURA 75000 y en critico 130000 en lugar de cura como base el 450% del poder con hechizo esto segun el change log de 7.1.0 (Mon Oct 24 2016) Build 22797

http://es.wowhead.com/spell=19750/destello-de-luz#changelog

**Comment by searum** [comment]
fix
