### ISSUE TITLE
SPELL BALUARTE DE ORDEN-PASIVA VERAGUARDIA -PALADIN

### ISSUE THREAD

**Issue by Killerbeer1** [ColossusWoW/ColossusWoW-Legion-Bugtracker#226]
La pasiva Baluarte de orden te protege como base protege 20 puntos en lugar de proteger el 
Escudo de vengador también te protege durante 8 sec y absorbe un 50% del daño que haya infligido. esto segun el change log 7.1.0 (Mon Oct 24 2016) Build 22758

http://es.wowhead.com/spell=209389/baluarte-de-orden

**Comment by searum** [comment]
fix
