### ISSUE TITLE
SPELL LUZ DE LOS TITANES PASIVA VERAGUARDIA-PALADIN

### ISSUE THREAD

**Issue by Killerbeer1** [ColossusWoW/ColossusWoW-Legion-Bugtracker#227]
Sana 0 puntos durante 15 segundos en lugar de curar el 500% del poder de ataque durante eso 15 segundos esto segundo el change log 7.0.3 (Mon Jul 18 2016) Build 21996

http://es.wowhead.com/spell=209539/luz-de-los-titanes#changelog

**Comment by searum** [comment]
fix
