### ISSUE TITLE
invocar infernal off- brujo afli

### ISSUE THREAD

**Issue by kranstein** [ColossusWoW/ColossusWoW-Legion-Bugtracker#233]
no me deja invocar al infernal, esta off el hechizo

http://es.wowhead.com/spell=1122/invocar-infernal

**Comment by searum** [comment]
y no será que no tienes fragmentos de alma? lo invoca bien

**Comment by kranstein** [comment]
no tengo fragmentos, por eso envie el bug de los fragmentos del arma que no
me cargan nunca


2016-12-14 21:12 GMT-06:00 searum <notifications@github.com>:
