### ISSUE TITLE
circulo demoniaco off- brujo afliccion

### ISSUE THREAD

**Issue by kranstein** [ColossusWoW/ColossusWoW-Legion-Bugtracker#234]
no me deja transportarme al circulo creado, dejo link de ambos hechizos, el que crea el circulo de primero y el que se utiliza para transportarse al circulo demoniaco 

http://es.wowhead.com/spell=60854/circulo-demoniaco

http://es.wowhead.com/spell=48020/circulo-demoniaco

**Comment by searum** [comment]
fix
