### ISSUE TITLE
DAÑO GENERAL DEL BRUJO

### ISSUE THREAD

**Issue by kranstein** [ColossusWoW/ColossusWoW-Legion-Bugtracker#235]
Podrian revisar el daño del brujo afli, registro daños a un npc lvl 14 de 22 de golpe.

http://es.wowhead.com/warlock-abilities

**Comment by searum** [comment]
este reporte no me sirve...

**Comment by kranstein** [comment]
esque no supe como asociarlo a wow head, dure 30 min matando un rare lvl
100, eso es un poco anormal, y poquito daño

2016-12-14 21:27 GMT-06:00 searum <notifications@github.com>:
