### ISSUE TITLE
Spell Ojo de Tyr VERAGUARDIA-PALADIN

### ISSUE THREAD

**Issue by Killerbeer1** [ColossusWoW/ColossusWoW-Legion-Bugtracker#238]
El spell ojo de tyr hace 1 de daño en lugar de hacer el 270% del poder de ataque segundo 
el change log 7.1.0 (Mon Oct 24 2016) Build 22636
http://es.wowhead.com/spell=209202/ojo-de-tyr

**Comment by searum** [comment]
fix
