### ISSUE TITLE
Bug spells de Mago - Descarga de escarcha y Dedos de escarcha (pasivo)

### ISSUE THREAD

**Issue by davidzoque** [ColossusWoW/ColossusWoW-Legion-Bugtracker#24]
Descargca de escarcha no relentia el 30% de velocidad de movimiento al objetivo impactado.

http://es.wowhead.com/spell=116/descarga-de-escarcha

El pasivo dedos de escarcha no llega activarse nunca.

http://es.wowhead.com/spell=44544/dedos-de-escarcha

**Comment by searum** [comment]
fix
