### ISSUE TITLE
SPELL DISPERSION DE LA SOMBRAS VERAGUARDIA-PALADIN

### ISSUE THREAD

**Issue by Killerbeer1** [ColossusWoW/ColossusWoW-Legion-Bugtracker#242]
EL SPELL DISPERSION DE LA SOMBRAS no aumenta la sanacion de luz del protector los porcentajes por rasgo que su maximo es 16% y su minimo 6% segun el change log 7.1.0 (Mon Oct 24 2016) Build 22636

http://es.wowhead.com/spell=209223/dispersion-de-las-sombras

**Comment by searum** [comment]
fix
