### ISSUE TITLE
[Re-open] Npc Vendedor de monturas issues

### ISSUE THREAD

**Issue by davidzoque** [ColossusWoW/ColossusWoW-Legion-Bugtracker#25]
El npc encargado de vender monturas de la raza Orca no vende nada.

http://es.wowhead.com/npc=3362/ogunaro-correlobo

El npc encargado de vender monturas de la raza elfo de noche no vende nada.

http://es.wowhead.com/npc=4730/lelanai

El npc encargado de vender monturas de la raza elfo de sangre no vende nada.

http://es.wowhead.com/npc=16264/winaestra

Asi mismo parecen ser las de todas las razas.
Habian marcado la anterio como corregido, pero aun sigue el fallo.

**Comment by Ragebones** [comment]
Esta corregido, pero debe de tener un fallo el vendedor con las clases y la reputacion, vamos a revisarlo.

**Comment by searum** [comment]
De igual manera las correcciones no se aplicarán al servidor instantáneamente.  dar un margen de tiempo de 1 o 2 días,  si persiste entonces reabrir el fallo
