### ISSUE TITLE
Instrutores de Profession BUG

### ISSUE THREAD

**Issue by tomasgx** [ColossusWoW/ColossusWoW-Legion-Bugtracker#26]
los instructores de herreria no muestran ni dialogo. (les das click y se quedan hay parados). son los instructores ya que lo he intentado con los de villadorada, ventromenta, bosque de ocaso. y todos estan igual.

linkeo el link de herreria donde salen todos los instructores.
http://es.wowhead.com/spell=29844/herreria#taught-by-npc
[http://es.wowhead.com/spell=29844/herreria#taught-by-npc](url)

los instructores de cocina estan igual
http://es.wowhead.com/spell=33359/cocina#taught-by-npc
[http://es.wowhead.com/spell=33359/cocina#taught-by-npc](url)

los instructores de primeros auxilios igual
http://es.wowhead.com/spell=45542/primeros-auxilios#taught-by-npc
[http://es.wowhead.com/spell=45542/primeros-auxilios#taught-by-npc](url)

instrutores de pesca igual
http://es.wowhead.com/search?q=Instructor+de+Pesca
[http://es.wowhead.com/search?q=Instructor+de+Pesca](url)

esos fue los que vi pero recomiendo revisar las demas profesiones (que lo mas probable es que estan igual).

**Comment by searum** [comment]
Facilitame las ids de los instructores si pudieras por favor, asi los arreglo más rápido y puedo continuar mientras con otras cosas. Gracias.

**Comment by tomasgx** [comment]
no se vien como se saca de npc ya que nunca me he interesadoen eso, solo me gusta jugar XD. de todas formas si se un poco pero como dije de ncp no se bien si cual de estos es asi que pondre ambos.

Therum Forjahonda <Instructor de herrería>
id="dsgndslgn464d"
displayId: 3307

Gelman Petramano <Instructor de minería>
id="dsgndslgn464d"
displayId: 3308

almenos esos 2 por ahora son los que me interesan

**Comment by Ragebones** [comment]
Tomasgx las id del npc son lo mismo que en wowhead has copiado:
http://es.wowhead.com/spell=29844/herreria#taught-by-npc

si te fijas donde pone spell=29844

la spell es= 29844

cuando veas un instructor que no funcione coge el nombre y buscalo en wowhead y comparte el link en el bugtracker, ya que nos facilita el trabajo.

**Comment by tomasgx** [comment]
oh bueno los link de los instrucctores seria
herreria
Herrero Argus <Instructor de herrería>
http://es.wowhead.com/npc=514/herrero-argus

Therum Forjahonda <Instructor de herrería>
http://es.wowhead.com/npc=5511/therum-forjahonda

Mineria
Gelman Petramano <Instructor de minería>
http://es.wowhead.com/npc=5513/gelman-petramano

cocina
Stephen Lomocenteno <Instructor de cocina>
http://es.wowhead.com/npc=5482/stephen-lomocenteno

Robby Flay <Chef principal>
http://es.wowhead.com/npc=42288/robby-flay

pesca
Arnold Leland <Instructor de pesca>
http://es.wowhead.com/npc=5493/arnold-leland

este es el instructor que enseña todas las profesiones en bosque de elwynn
Lien Farner <Instructor de profesión>
http://es.wowhead.com/npc=47384/lien-farner

esos serian solo los de ventor y bosque de elwynn

**Comment by Ragebones** [comment]
Gracias, vamos a reparar el problema.

**Comment by searum** [comment]
Les recomiendo un addon para poder sacar las ids muy facilmente. idTip se llama.

**Comment by searum** [comment]
fix
