### ISSUE TITLE
Los NPC tienen un bug

### ISSUE THREAD

**Issue by Killerbeer1** [ColossusWoW/ColossusWoW-Legion-Bugtracker#265]
LOS NPC CUANDO ENTRAN EN COMBATE SE CAEN DEL MAPA,Y SI ESTA EN CASTILLOS SE CAEN AL FONDO DEL CASTILLO AL ENTRAR EN COMBATE O INTERACTUAR

**Comment by searum** [comment]
VALE TIO PERO NO HACE FALTA ESCRIBIR EN MAYÚSCULAS
