### ISSUE TITLE
Bug del chaman 

### ISSUE THREAD

**Issue by Zoombiie** [ColossusWoW/ColossusWoW-Legion-Bugtracker#266]
Todos los totem estan bug como igual que los talentos como :  
Maestría de Tótem ( nivel 15 )
Tótem de carga de viento ( nivel 30 )
Tótem pillaterra, Tótem vudú 
Tótem oleada de relámpagos ( nivel 45 )

Habilidades: 
No se ve el vorágine en elemental o en mejora ( habilidades en general no sirven en todas las spec, elemental, mejora, heal. 
Descarga de relámpagos poco daño
Oleada de sanación ( no cura )  
Elemental de fuego, elemental de tierra no sirve 
Tótem nexo terrestre tampoco sirve como ya mencionado anteriormente 

Mejora:
Lengua de fuego daño 1 
Muerde piedras daño 1 
Estigma de escarcha daño 1 
Hendimiento no hace daño 
Espíritu feral no salen los lobos
embestida feral no hace el daño que dice

Aquí están algunos de los bugs que encontré que son muy importantes para el chaman

**Comment by searum** [comment]
fix la mayoria, si falta alguno reportalos por separado en nuevos issues, gracias.
