### ISSUE TITLE
me faltan hechizos! DH

### ISSUE THREAD

**Issue by kranstein** [ColossusWoW/ColossusWoW-Legion-Bugtracker#268]
queria reportar que me faltan hechizos con el DH Dps, son los iguientes: 
Danza de Hojas
Encarcelar
Lanzar Guja
Metamorfosis
Disiparse
http://es.wowhead.com/demon-hunter-abilities

Les digo que hice todas las quest, excepto la de matar un boss que estaba bug, erroneamente no reporte esa mision, espero su respuesta o ayuda

**Comment by Drakfire** [comment]
Buenas! es imposible que hayas echo todas las misiones! la misión de matar a ese boss de la piedra angular es la que dices. si no haces esa misión no podrás seguir. cuando estés ingame pon ticket y te ayudaré. Todavía te falta pasar por las cámaras de las celadoras! y ahí te dan esas habilidades
