### ISSUE TITLE
drop ?

### ISSUE THREAD

**Issue by tomasgx** [ColossusWoW/ColossusWoW-Legion-Bugtracker#27]
me he dado cuenta que al menos que sea un elite raro, los add no dropean nada de ropa, si dan las cosas normales que sueltan pero no ropa ni amas. (quizas sea algo de la nueva exp, no se), pero igual me todo la molestia de informar, ya que los add estan causando mucho daño y quiero pensar que es por la falta de equipamento y no con problemas en el sistema de daño del server.

**Comment by davidzoque** [comment]
De eso se queja mucha gente que les es muy dificil equiparse por que no les lootean cosas utiles y de repeso las quest tampoco les dan los rewards.

**Comment by Ragebones** [comment]
para eso esta el bugtracker para que reporteis todos los npc y podamos añadirlos.

**Comment by searum** [comment]
fix
