### ISSUE TITLE
alas demon hunter

### ISSUE THREAD

**Issue by idorichan** [ColossusWoW/ColossusWoW-Legion-Bugtracker#270]
las alas estan bug, no planean y al dar el doble salto no dan impulso

**Comment by Drakfire** [comment]
Buenas! las alas si funcionan!, si da el doble salto. El DH si planea pero el problema esque no planea como tiene que ser, cae muy rápido y tendría que caer mas lento y desplazarse mas rapido.
[Planear](http://es.wowhead.com/spell=197130/planear)
