### ISSUE TITLE
pantalla negra

### ISSUE THREAD

**Issue by idorichan** [ColossusWoW/ColossusWoW-Legion-Bugtracker#271]
la sala de los illidari despues de que se autocompletara la pmision "piedra angular" (obra y gracias del espiritu santo) me transportaron allí jaja

**Comment by idorichan** [comment]
ahora tengo pantalla negra en todas partes

**Comment by Drakfire** [comment]
Solucionado para el jugador!. 
Comentario para los DEV : hay que tener presente que todos los DH que pasan a la sala de los illidari en la cámara de las celadoras hay que hacerles .unaura all porque aparecen con una pantalla en negro despues de la pantalla de carga.

**Comment by searum** [comment]
eso ya se reparó.
