### ISSUE TITLE
Migracion Bug

### ISSUE THREAD

**Issue by necrotyck** [ColossusWoW/ColossusWoW-Legion-Bugtracker#273]
Hola, llevo tratando de migrar mi PJ de Firestorm como 12 horas esperando y nada siempre que quiero migrar me dice que no tengo migraciones y hago todos los pasos muy bien, por favor necesito ayuda con eso gracias

**Comment by searum** [comment]
eso no es un bug, es que no tienes más migraciones. el sistema te ha descontado 2 migraciones que tienes gratis, no hay más de 2.
