### ISSUE TITLE
Testarazo Druida-Feral BUG

### ISSUE THREAD

**Issue by necrotyck** [ColossusWoW/ColossusWoW-Legion-Bugtracker#275]
Testarazo es unas de las habilidades del Druida Feral en donde
Requiere Forma felina, Forma de oso
Cargas y das un testarazo al cráneo del objetivo, lo que interrumpe el lanzamiento de hechizos e impide que se lancen hechizos de esa escuela durante 4 sec.

Su bug es que ni carga ni hace nada cuando se utiliza simplemente no hace nada el PJ se queda igual como estaba y la habilidad si aparece como si se hubiera utilizado necesito que me ayuden con esto gracias

**Comment by searum** [comment]
fix
