### ISSUE TITLE
bug vendedores

### ISSUE THREAD

**Issue by tomasgx** [ColossusWoW/ColossusWoW-Legion-Bugtracker#28]
hay diferentes vendedores bug que no muestran la interfas de venta sino que solo dan un dialogo 

colo solo 2 de lo que he visto ya que son los 2 que vende lo que necesito

Brooke Petratrenza <Suministros de minería>
http://es.wowhead.com/npc=5514/brooke-petratrenza

Kaita Forjahonda <Suministros de herrería>
http://es.wowhead.com/npc=5512/kaita-forjahonda

**Comment by searum** [comment]
fix
