### ISSUE TITLE
Bug_Quest_Gilneas Salvar KrennanAranas

### ISSUE THREAD

**Issue by Argocam** [ColossusWoW/ColossusWoW-Legion-Bugtracker#29]
Buenas gente

La quest de Salvar a Krennan Aranas anda bug, no aparece el caballo, en cambio com que uno se vuelve invisible, suena la músuca de cuando uno es un muerto y no hay forma de completarla y avanzar.

http://www.wowhead.com/quest=14293/save-krennan-aranas

Gracias

**Comment by searum** [comment]
fix
