### ISSUE TITLE
Quest: The Keys Stone Bug

### ISSUE THREAD

**Issue by screwone** [ColossusWoW/ColossusWoW-Legion-Bugtracker#33]
No me da hacer esa quest no me salen los pj y el boos no se l epuede pegar 👍 Att Miloh

**Comment by Misimouse** [comment]
Gracias por el reporte, pero para próximos reportes sería de agradecer poner el enlace a wowhead :)

**Comment by screwone** [comment]
http://es.wowhead.com/quest=38728/the-keystone

**Comment by Misimouse** [comment]
La misión ya se puede completar faltan algunos NPC's que ayudan al jugador en la misión pero por ahora no dispongo de esos datos en cuanto los tenga los añadiremos.
