### ISSUE TITLE
Spells mago Issues

### ISSUE THREAD

**Issue by davidzoque** [ColossusWoW/ColossusWoW-Legion-Bugtracker#34]
El pasivo dedos de escarcha no hace que el daño de Lanza de escarcha (http://es.wowhead.com/spell=63562/lanza-de-escarcha) no se aumente el daño como si el objetivo estuviera congelado (triple daño).

http://es.wowhead.com/spell=44544/dedos-de-escarcha

-La habilidad de la pet de mago Descarga Acuatica (http://es.wowhead.com/spell=31707/descarga-acuatica) continua presentando un bajo daño que no esta acorde con lo que el texto dice.

**Comment by searum** [comment]
ok ahora lo miro

**Comment by searum** [comment]
fix
