### ISSUE TITLE
Problemas en Hechizos

### ISSUE THREAD

**Issue by screwone** [ColossusWoW/ColossusWoW-Legion-Bugtracker#36]
Esto le pasa a mi demon hunter, no genera Furia, el unico Hechizo que me da es http://es.wowhead.com/spell=195072/carga-vil y sin furia no me activa los demas spell, quisiera revisar eso por favor tambien.
Pj: Miloh, Alianza, Demon Hunter, level 100

**Comment by searum** [comment]
Pero lo que tendrias que reportar es el spell que no te da furia.

**Comment by searum** [comment]
Vuelve a crear otro reporte diciendo el spell que no genera furia. Gracias
