### ISSUE TITLE
Separación (Spell Cazador)

### ISSUE THREAD

**Issue by HansLanda2** [ColossusWoW/ColossusWoW-Legion-Bugtracker#372]
No se puede usar mientras se salta http://es.wowhead.com/spell=781/separacion

**Comment by timh52280** [comment]
Cierro porque he probado el spell y si se puede usar mientras saltas solo que para poder usar el spell es necesario estar primero en combate.

**Comment by thebigfer94** [comment]
Pero no deberia de funcionar solo en combate.

**Comment by timh52280** [comment]
Ok déjame revisar algunos vídeos, si tenéis pruebas de que debe funcionar aunque no se este en combate, colocarlas aquí,

**Comment by timh52280** [comment]
Fixed.
