### ISSUE TITLE
Bug De Misiones y Hechizos de los Demon Hunters

### ISSUE THREAD

**Issue by MJTomoky** [ColossusWoW/ColossusWoW-Legion-Bugtracker#38]
**BUG De Los Cazadores De Demonios!**
- Mision " Liberalos " ID Mision =3372 , no entrega la experiencia que dice ni el item ID=128952 que es la pechera de los DH.
- Mision " Conoce a los Illidari: Las shivarras " ID Mision =38765 , no entrega la experiencia que dice ni el item ID =133316 que es la pierna de los DH.
- Mision " Sus números son legión " ID Mision =38819 , no entrega la experiencia que dice que da ni el item ID=128950 que son las hombreras para los DH Y No se puede entregar.
- Mision " Adentrarse en el Nido Fétido " ID Mision =38725 , no entrega la experiencia que dice que deberia dar
- Hechizo de los DH " Metamorfosis "  ID de Hechizo =162264 , no da ningun  efecto  
  ( Saltas en el aire y aterrizas con una fuerza explosiva, lo que inflige (200% of Attack power) p. de daño de Caos a los enemigos en un radio de 8 m y los aturde durante 3 s.

Al aterrizar, te transformas en un demonio infernal durante 30 s, lo que potencia considerablemente tus facultades Golpe de caos y Danza de hojas, y obtienes un 25% de celeridad.).
- Hechizo  de los DH " Consumo de magia " ID de Hechizo =183752 , no da ningun efecto 
  ( Interrumpe el lanzamiento de hechizos del enemigo, lo que le bloquea esa escuela de magia durante 3 s.Almas destrozadas
  Genera 50 p. de furia si se interrumpe con éxito. ).
- Mision " La piedra angular " ID Mision =10257 , no se puede completar ni activar porque el npc se bugea y se cae.

**Comment by searum** [comment]
Deberia de estar todo fix en la próxima compilación. Si notas que algo no está arreglado cuando actualice el servidor vuelve a reportarlo pero por separado. Gracias.
