### ISSUE TITLE
Sistema de reputacion- Profesiones 

### ISSUE THREAD

**Issue by renzo101999** [ColossusWoW/ColossusWoW-Legion-Bugtracker#45]
Al hacer misiones o matando NPC  no sube la reputacion te tu faccion y neutrales Horda, no se si pasara con la alianza

La profecion mineria no se puede picar minerales arreglenlo porfavor

Muy aparte de eso no aparece el NPC que te da la mision 
http://es.wowhead.com/quest=31853/todos-a-bordo
Para poder ir a pandarian

**Comment by searum** [comment]
Fix
