### ISSUE TITLE
tablero de misiones

### ISSUE THREAD

**Issue by tomasgx** [ColossusWoW/ColossusWoW-Legion-Bugtracker#47]
no da las misiones de draenor 

http://es.wowhead.com/quest=34398/el-portal-oscuro

http://es.wowhead.com/quest=36498/invasion-de-la-horda-de-hierro

y la mision de lvl90 para legion

http://es.wowhead.com/quest=40519/la-legion-ha-vuelto

**Comment by searum** [comment]
fix
