### ISSUE TITLE
AYUDA pantalla negra

### ISSUE THREAD

**Issue by tomasgx** [ColossusWoW/ColossusWoW-Legion-Bugtracker#53]
saludos, he dejado varios tikect, y un msj en la pagina de facebook pero no he conceguido soporte aun asi que hag el reporte aka.

he creado un cazador de demonios y realizado casi todas las misiones hasta
"regreso al templo oscuro" (no consegui la mision en wowhead solo sale el video)
el hecho es que la mision se paga e el portal y te pone la cinematica donde maiev nos captura y despues nos libera.. termina la cinematica y la pantalla del juego me quedo asi

https://postimg.org/image/y4jh6acsl/

ya he relogeado, borre la carpeta cache, use piedra hogar, deje que me mataran ( cuando mori si vi normal el juego se veia mi espiritu y pude ir a mi cuerpo y revivirme) al revivirme la pantalla se puzo negra otraves, me deje matar nuevamente y me revivi en el angel y volvio a ponerse negar la pantalla.

necesito ayuda mi pj se llama girimi

**Comment by searum** [comment]
pon ticket ingame para que te quiten las auras.
