### ISSUE TITLE
error al estar muerto.

### ISSUE THREAD

**Issue by tomasgx** [ColossusWoW/ColossusWoW-Legion-Bugtracker#58]
he notado diferentes fallos al estar muerto.
1. algunos angeles dicen "entidad desconocida" 
   y no funcionan (ahora que teng el addon de las ID
   cuando consiga uno lo reporto)
2. cuando se desconecta estando muerto el 
   alma se desvincula del cuerpo y ya no se puede revivir
   posteo la imagen de prueba estoy en frente de mi cuerpo
   y no me da la para revivir

https://postimg.org/image/xy588l5g1/

**Comment by searum** [comment]
fix, lo de los npcs es cuestion de ir viendolos y reparandolos.
