### ISSUE TITLE
 Mazmorras sin nada adentro

### ISSUE THREAD

**Issue by renzo101999** [ColossusWoW/ColossusWoW-Legion-Bugtracker#67]
1.- Salas Sethekk - Terralende - Bosque del terokkar
http://es.wowhead.com/zone=3791/salas-sethekk

2.- Reposo del dragon - Rasganorte - Cementerio de dragones
http://es.wowhead.com/zone=4987/el-sagrario-rubi

3.- Guarida de onixya - Kalimdor - Marjal Revolcafango
http://es.wowhead.com/zone=2159/guarida-de-onyxia

4.- Trono de los cuatro vientos - Kalimdor - Uldum
http://es.wowhead.com/zone=5638/trono-de-los-cuatro-vientos

5.- Templo de ahn´Qiraj - Kalimdor - Silithus
http://es.wowhead.com/zone=3428/ahnqiraj#achievements

6.- Zul´Farrak - Kalimdor - Tanaris
http://es.wowhead.com/zone=1176/zulfarrak

7.- Ciudadela de Corona de hielo - Rasganorte - Corona de Hielo
http://es.wowhead.com/zone=4812/ciudadela-de-la-corona-de-hielo
                        En esta mazmorra al finalizar "lady susurramuerte" y antes de "Batalla de las aeronaves de corona de hielo", Te bota el server      , si se encuentran todos los NPC

8.- Forja de  almas - Rasganorte - Corona de Hielo
http://es.wowhead.com/zone=4809/la-forja-de-almas  
                        No se puede salir al entrar a la instancia

9.- Cámaras de Relámpago - Rasganorte - Cumbres tormentosas
http://es.wowhead.com/zone=4272/camaras-de-relampagos

10.- Ulduar - Rasganorte - Cumbres tormentosas
http://es.wowhead.com/zone=4273/ulduar
                       Te bota el server  , se encuentran todos los  NPC

11.- Camaras de piedra - Rasganorte - Cumbres tormentosas 
http://es.wowhead.com/zone=4264/camaras-de-piedra

12.- Prueba del Cruzado - Rasganorte - Corona de Hielo
http://es.wowhead.com/zone=4722/prueba-del-cruzado
                        No se puede salir al entrar en la instancia 
13.-  El bastión Violeta  - Rasganorte - Dalaran 
http://es.wowhead.com/zone=4415/el-bastion-violeta

14.-  El Sagrario Obsidiana - Rasganorte - Cementerio de dragones
http://es.wowhead.com/zone=4493/el-sagrario-obsidiana

15.-  Ojo de la Eternidad - Terrallende - Tormenta abisal 
http://es.wowhead.com/zone=4500/el-ojo-de-la-eternidad

16.-  Templo Oscuro - Terrallende - Valle Sombra luna 
http://es.wowhead.com/zone=3959/templo-oscuro

17.- Banca del Magister - Reinos del Este - Islas de Quel´Danas.
http://es.wowhead.com/zone=4131/bancal-del-magister

18.-Pináculo de Utgarde - Rasganorte- Firodo Aquilonal
http://es.wowhead.com/utgarde-pinnacle

19.-

**Comment by Ripfakeglad** [comment]
1.-El npc Paulie no vende el item correspondiente.
**NPC** http://es.wowhead.com/npc=87501/paulie#sells
**ITEM** http://es.wowhead.com/item=116789/apisonadora-de-campeon

**Comment by searum** [comment]
fix
