### ISSUE TITLE
problema de aplicacion

### ISSUE THREAD

**Issue by felixel0** [ColossusWoW/ColossusWoW-Legion-Bugtracker#79]
Buenos dias,
necesito un gm o a kael para que me ayuden a arreglar la aplicacion del juego se me distorciona y no se que hacer, por favor ayuda URGENTE, tengo teamviewer por si necesitan ayudaaaa.
si quieren me contactan por el facebooko please. anres Felipe valencia

**Comment by Drakfire** [comment]
Hola felixel0, dado tu problema no podemos ayudarte, tienes que especificar mas detalladamente tu problema, y así podremos ayudarte a solucionarlo.
Muchas gracias. disfruta de tu estancia en el servidor!
ATT: Tito
