### ISSUE TITLE
BUG'S Que posee la clase paladin SPEC PROTECCION 

### ISSUE THREAD

**Issue by Killerbeer1** [ColossusWoW/ColossusWoW-Legion-Bugtracker#80]
#66

Las habilidades 
Corcel divino 
Al utilizarse el paladin no se monta en la respectiva montura 
http://www.wowhead.com/spell=190784
 Luz Cegadora 
No hace efecto lo que equivale hace la animacion mas no pone el aturdimiento 
http://www.wowhead.com/spell=115750
Consagración 
No hace su daño respectivo ni otorga los bonus de armadura (Bonus de armadura hago referencia al % de buff que aumenta de daño recibido con el escudo del honrado)ni de sanacion que deberia (Con luz del protector)
http://www.wowhead.com/spell=26573
Luz del protector 
No sana el porcentage que deberia sanar si no que hace 35 puntos de sanación
y al usarse el skill en consagracion el skill no hace su aumento respectivo de sanacion 
http://www.wowhead.com/spell=184092

El bloquear ocasiona que el paladin muera anexo link del porque
http://imgur.com/MVUMIcs

**Comment by searum** [comment]
y otra vez más...
