### ISSUE TITLE
El portal que dirige a infralar y ashran 

### ISSUE THREAD

**Issue by Killerbeer1** [ColossusWoW/ColossusWoW-Legion-Bugtracker#83]
Los portales que conectan con INFRALAR y ASHRAN no se pueden acceder a ellos lo que hacen imposible el ir a dichos sitios

**Comment by Drakfire** [comment]
Hola Killerbeer1, Gracias por tu reporte.
El portal a Infralar que está en ventormenta en la zona de portales. no funciona, te dice esto exactamente "Agua poca profunda" 
ID del portal: 207693
Infralar: http://es.wowhead.com/deepholm
Mas información:
al coger el portal de ventormenta a infralar tendría que dejarnos justo adentro del templo de la tierra, justo delante de unos portales que se verán cuando se entra.

**Comment by Drakfire** [comment]
El portal a ashran no funciona
Spell de mago: no lleva a ashran (spell: http://www.wowdb.com/spells/176246-portal-stormshield )
Portal en ventormenta: (tendría que haber uno pero no está. 

## Vídeo explicativo de donde tendría que estar. ( https://www.youtube.com/watch?v=Z0dMbYjW0n0 )

Portal de ashran en orgrimmar, está pero no funciona, no te lleva a su destino.
ID (237738)
Fotos
![image](https://cloud.githubusercontent.com/assets/7884110/19587524/3597130a-975f-11e6-8787-9b0edc0a21ab.png)

 segunda imagen: https://www.mediafire.com/?5pks5nndwvx5f44

**Comment by searum** [comment]
Para coger los portales primero tenéis que realizar las misiones del tablón. Si es cierto que el portal a Ashran no funcionaba, ese está reparado ya pero los otros tenéis que hacer las misiones.
