### ISSUE TITLE
Hojas de demonio [Spell] cazador de demonios

### ISSUE THREAD

**Issue by Drakfire** [ColossusWoW/ColossusWoW-Legion-Bugtracker#89]
La spell de talento [Hojas de demonio](http://es.wowhead.com/spell=203555/hojas-de-demonio) 
No funciona. como bien dice la información:  
## **Tus ataques automáticos tienen un 75% de probabilidad de infligir daño de las Sombras extra y de generar furia.**

Bien, pues No genera furia y muy rara vez inflige daño de las sombras, por decir muy rara vez me refiero a poco de 47 mobs solo a 3

**Comment by searum** [comment]
fix
