### ISSUE TITLE
[Spell Bug]

### ISSUE THREAD

**Issue by Ripfakeglad** [ColossusWoW/ColossusWoW-Legion-Bugtracker#92]
La Spell Hojas demoniacas está bug.
spell=203555
Link; http://es.wowhead.com/spell=203555/hojas-de-demonio

**Comment by timh52280** [comment]
Podrías especificar mas las cuestiones en que falla el spell por favor? Así nos sera mas facil fixearlo.

**Comment by searum** [comment]
fix
