### ISSUE TITLE
Evento de halloween

### ISSUE THREAD

**Issue by renzo101999** [ColossusWoW/ColossusWoW-Legion-Bugtracker#93]
ESTOS ERRORES ESTÁN VISTO DESDE LA PERSPECTIVA DE LA HORDA.

Básicamente  los "cubos de caramelos"  ( http://es.wowhead.com/object=208162/cubo-de-caramelos )
de ciertas zonas listadas a continuación  no te dan los "Puñados de golosinas"
( http://es.wowhead.com/item=37586/punado-de-golosinas )

Prueba:   http://www.uppic.es/image/0H6

RASGANORTE:

Tundra Boreal   http://www.uppic.es/image/0Hk
1.- Tundra Boreal   76,37   Poblado Taunka'le
2.- Tundra Boreal   78,49   Unu'pe
3.- Tundra Boreal   42,54   Bastión Grito de Guerra

Cementerio de Dragones   http://www.uppic.es/image/0Hr
1.- Cementerio de Dragones  38,46   Martillo de Agmar
2.- Cementerio de Dragones  60,54   Templo del Reposo del Dragón
3.- Cementerio de Dragones  77,63   Rencor Venenoso
4.- Cementerio de Dragones  48,75   Puerto Moa'ki

Fiordo Aquilonal    http://www.uppic.es/image/0HQ
1.- Fiordo Aquilonal         80,31       Campo Venganza
2.- Fiordo Aquilonal         49,11       Campo Pezuña Invernal
3.- Fiordo Aquilonal         25,60        Komawa
4.- Fiordo Aquilonal     52,66       Nuevo Agamand

Las Cumbres Tormentosas  http://www.uppic.es/image/0Hw
1.- Las Cumbres Tormentosas     31,37   Refugio de Pedruscón
2.- Las Cumbres Tormentosas     41,86   K3
3.- Las Cumbres Tormentosas         68,51   Campamento Tunka'lo

Dalaran     http://www.uppic.es/image/0Hy
1.-  Dalaran    35,56   Las Cloacas
2.- Dalaran 50,39   Salón Juego de Manos
3.- Dalaran 65,32   Santuario de Atracasol

KALIMDOR

Azshara.  http://www.uppic.es/image/0H8
1.- Azshara 57,50   Muelle Pantoque      http://www.uppic.es/image/0Hz

TERRALLENDE

Bosque de Terokkar.   http://www.uppic.es/image/0HJ

-Ciudad de Shattrath.  http://www.uppic.es/image/0HO
1.- Ciudad de Shattrath 28,48 / 56,82   Alto Aldor / Alto Arúspice

CATACLYSM
Vashj´ir
No se puede llegar el barco de la horda esta bug 

PANDARIA
Recientemente ya no se puede ir ya que el portal no siver en ogrimar

**Comment by searum** [comment]
todo fix para la siguiente compilación ;)
