### ISSUE TITLE
Sus números son legión (Misión bug) CAZADOR DE DEMONIOS

### ISSUE THREAD

**Issue by Drakfire** [ColossusWoW/ColossusWoW-Legion-Bugtracker#98]
Al hacer lo que te pide la misión todo perfecto, Pero a la hora de completarla con el NPC no se completa. y por culpa de ello no se pueden seguir las misiones del cazador de demonios.
[Misión](http://es.wowhead.com/quest=38819/sus-numeros-son-legion)
[NPC de completar](http://es.wowhead.com/npc=93127/kayn-furia-del-sol)

**Comment by searum** [comment]
fix
